Div support for fe functions
gridap/Gridap.jl pull request #650
Opened 2021-08-26 05:37 UTC by amartinhuertas

This PR can be reviewed straight away

2021-09-06 07:00 UTC, fverdugo requested changes
> IMPORTANT NOTE: This PR can ONLY be accepted AFTER PR #638 , PR #651, and PR #652 which are still pending

Waiting

2021-09-08 02:46 UTC, amartinhuertas commented
> Waiting

@fverdugo ... This PR can be reviewed straight away

Thanks!

2021-09-08 04:58 UTC, fverdugo approved these changes

2021-09-08 04:59 UTC, merged

2021-09-08 05:04 UTC, amartinhuertas commented
Hi @fverdugo ... do u think we can release a new patch version with the latest PRs or better to wait for on-going devs?