collect & comprehension on TransientFESolutions
gridap/Gridap.jl pull request #833
Opened 2022-09-24 13:58 UTC by Antoinemarteau

2022-10-17 12:40 UTC, Antoinemarteau commented
Hi @fverdugo, I take the leberty to ping you to get feedback of this PR.

( I implemented the copy function for CellDatum, but used list comprehension to write the tests, so I wait for this pr to be resolved to open another one )

2022-10-17 14:13 UTC, fverdugo requested changes
@Antoinemarteau Thanks for this PR. Seting the length as unknown is the way to go, also in my opinion.

Can you please add some test?

 A very small one like 
 ```julia
@test length([uh for un in uh_transine])==nsteps
```
 would be enough.

2022-10-18 09:09 UTC, Antoinemarteau commented
@fverdugo thanks for the feedback :)
I added the test.

2022-10-18 11:41 UTC, fverdugo approved these changes

2022-10-18 11:50 UTC, merged